[package]
name = "my_project"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day01"
path = "adventofcode_2025/day_1.rs"

[[bin]]
name = "day02"
path = "adventofcode_2025/day_2.rs"

[dependencies]
